name: fl_tooltip
description: A new Flutter package project.
version: 0.0.1-alpha.0
homepage:

environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
