name: fl_tooltip
description: Flutter package for showing tooltip using Flutter's Overlay widget
version: 0.0.1-alpha.0
repository: https://github.com/iandis/fl-tooltip
issue_tracker: https://github.com/iandis/fl-tooltip/issues

environment:
  sdk: '>=2.18.6 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
